In [49]:
import pandas as pd
import numpy as np

In [41]:
%%time
df_loc = "../tests/bruno/df_new.hdf"
df = pd.read_hdf(df_loc, key="df")
df = df.sort_values(by=["frame", "ID"])

CPU times: user 1.03 s, sys: 547 ms, total: 1.58 s
Wall time: 1.63 s


In [16]:
%%time
df_list = [df_loc.to_numpy() for _, df_loc in df.groupby('frame')]

CPU times: user 11.1 s, sys: 272 ms, total: 11.4 s
Wall time: 11.3 s


In [68]:
%%timeit
n_flies = df.ID.unique().size
n_features = df.shape[1]
df_reshaped = df.to_numpy().reshape(-1, n_flies, n_features)
df_reshaped = np.around(df_reshaped).astype(int) # everything must go with ints

243 ms ± 8.47 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [30]:
df_reshaped[0, :, 4]

array([0., 2., 1., 1., 1., 0., 0., 2., 0., 2., 2., 0., 0., 2., 1., 1., 1.,
       1., 1., 1., 0., 2., 0., 0., 2., 0., 3., 1., 2., 2., 2., 3., 3., 3.,
       3., 3., 3., 3., 3., 3.])

In [36]:
df.shape

(4318200, 5)

In [72]:
%%timeit
for frame_stuff in df_reshaped[:100]:
    a = frame_stuff.shape

15.7 µs ± 430 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [73]:
%%timeit
for idx in np.arange(100):
    a = df_reshaped[idx].shape

32.2 µs ± 1.69 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [74]:
%%timeit
for frame_stuff_i, frame_stuff_j in zip(df_reshaped[:100], df_reshaped[1:101]):
    a = frame_stuff_i.shape
    b = frame_stuff_j.shape

36.4 µs ± 1.19 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [75]:
%%timeit
for idx in np.arange(100):
    a = df_reshaped[idx].shape
    b = df_reshaped[idx + 1].shape

80.2 µs ± 1.09 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [59]:
frame_info = df_reshaped[0]

In [61]:
frame_info.shape

(40, 5)

In [62]:
from scipy.spatial import distance_matrix

In [63]:
distance_matrix(frame_info[:, 2:3], frame_info[:, 2:3])

array([[  0.        , 368.3994751 , 404.20147705, ...,   1.87780762,
         18.85351562,  80.68463135],
       [368.3994751 ,   0.        ,  35.80200195, ..., 370.27728271,
        387.25299072, 449.08410645],
       [404.20147705,  35.80200195,   0.        , ..., 406.07928467,
        423.05499268, 484.8861084 ],
       ...,
       [  1.87780762, 370.27728271, 406.07928467, ...,   0.        ,
         16.97570801,  78.80682373],
       [ 18.85351562, 387.25299072, 423.05499268, ...,  16.97570801,
          0.        ,  61.83111572],
       [ 80.68463135, 449.08410645, 484.8861084 , ...,  78.80682373,
         61.83111572,   0.        ]])

In [71]:
fordf_reshaped

array([[[9.90000000e+01, 0.00000000e+00, 8.69101074e+02, 4.55739838e+02,
         0.00000000e+00],
        [9.90000000e+01, 1.00000000e+00, 5.00701599e+02, 2.13673691e+02,
         2.00000000e+00],
        [9.90000000e+01, 2.00000000e+00, 4.64899597e+02, 8.18545593e+02,
         1.00000000e+00],
        ...,
        [9.90000000e+01, 3.70000000e+01, 8.70978882e+02, 5.71943787e+02,
         3.00000000e+00],
        [9.90000000e+01, 3.80000000e+01, 8.87954590e+02, 5.68587830e+02,
         3.00000000e+00],
        [9.90000000e+01, 3.90000000e+01, 9.49785706e+02, 7.94331543e+02,
         3.00000000e+00]],

       [[1.00000000e+02, 0.00000000e+00, 8.70785714e+02, 4.54571429e+02,
         0.00000000e+00],
        [1.00000000e+02, 1.00000000e+00, 5.01173913e+02, 2.13934783e+02,
         2.00000000e+00],
        [1.00000000e+02, 2.00000000e+00, 4.65028571e+02, 8.18314286e+02,
         1.00000000e+00],
        ...,
        [1.00000000e+02, 3.70000000e+01, 8.70875000e+02, 5.71958333e+02,
        